// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv90fOJqmTcUL7hBMD_Gaf1TBT79fTRS8',
    appId: '1:563583514872:android:2bab6c7b0bb1751072630d',
    messagingSenderId: '563583514872',
    projectId: 'sanalirademoapp',
    storageBucket: 'sanalirademoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkMkMqm4kKn9fC4slubwKe67nlrjWjW_E',
    appId: '1:563583514872:ios:5db27cb03d989e8272630d',
    messagingSenderId: '563583514872',
    projectId: 'sanalirademoapp',
    storageBucket: 'sanalirademoapp.appspot.com',
    androidClientId: '563583514872-p9jsn5a5seh0pero6onundckvkduqp49.apps.googleusercontent.com',
    iosClientId: '563583514872-euiuvq2rmglk2aau2s8988rji078320m.apps.googleusercontent.com',
    iosBundleId: 'com.sanaliratest.sanalira',
  );
}
